### ISSUE TITLE
Implementing policy upon key-value api 

### ISSUE THREAD

**Issue by andreamargheri** [sunfish-prj/Registry-Interface#2]
Re DM api, proceed with the implementation of the policy api

**Comment by andreamargheri** [comment]
[Policy API](https://github.com/sunfish-prj/SUNFISH-Platform-API/blob/master/RegistryInterfaceAPI/swagger/RegistryInterface.yaml) comprises tradiational management actioni for policies:

1. Policy **store** (to act like update in case the policy is already stored)
2. Policy **read**
3. Policy **delete**

additionally, as policies are assigned to a service to manage it, it supports the API 

4. Policy **polService** that, given a *service id*, returns *all the associated policies*. 

The Policy management is implemented upon a key-value store db that is offered by the decentralised infrastructure of the [Registry](https://github.com/sunfish-prj/Registry).

According to the current api, the state info to store for a policy is (*token* is used just for AuthN/Z, not included in the state):

- *requestorID*: identifier of the principal (eg component or admin) storing the policy
- *id*: **unique policy identifier** 
- *policy*: body of the policy into Base64 encoding
- *policyType*: identifying the policy type (eg *access*, *admin*, etc.) 
- *expirationTime*: storing expiration time
- *serviceID*: identifier of the service managed by the policy (state field optional due to *admin* policies do not refer to services)

Given a state entry to store (in order as before)

> req_1; p_1; {Pol}; A; TIME; S_1 

The state can be stored into <K,V> pairs according to different strategies: 

**Strategy 1: unique policy id** - 2 pairs per entry + Service-Policy association

1. <p_1, {Pol}>   -> policy body
2. <p_1, [req_1;A;TIME]> -> meta-data of the policy
3. <S_1, [p_1]>   -> a list of policy assigned to each service identifier

The first two entries can be stored into a single entry by means of structured data 

1. <p_1, [{Pol}; [req_1;A;TIME]]>

**Strategy 2: metadata acting as reference** 

1. <p_1+req_1+A+TIME, {Pol} -> all metadata (or some of them) to be used as policy identifier
2. <S_1, p_1+req_1+A+TIME> 

**Other strategy?**

Storing the list of policy assigned to Service identifiers are makes the realisation of the api *polService* easier. Otherwise, all the policy entries should be retrieved and their metadata evaluated singularly. 

---- 

**Open Issues**
- Which strategy to store the policy state?
- How to assign the Policy to multiple Services? I think we should add an API
- How the requestorID should be used? 
- Should we manage the serviceId?

**Comment by rsindper** [comment]
I think for storing a unique key-value pair, both Strategy 1 and 2 are fine. I prefer Strategy 1 as it supports a list of policies assigned to each service, which enables the single-service-multi-policies look-up. Besides, for a single-policy-multi-consumer(services) look-up, I think we can use the *serviceID* filed as a service list when implementing *PolicyStore* api, so that each policy can store a list of services that are consuming it. Another solution is, as @andreamargheri suggested, to add an API to support this function. Thanks.

**Comment by areiter** [comment]
>  Which strategy to store the policy state?

I think the first strategy is the way to go.
It's conform to the current Registry API specification, no changes to the API are required.

>  How to assign the Policy to multiple Services? I think we should add an API

I don't think that we need this functionality on storage level! Of course it would minimize the storage size, but this is not the goal of key-value like storages (like NoSQL - MongoDB). Just imagine the impact of changing a single policy linked to multiple services.

This is functionality which could be moved to user interface level, like:

- Provide a list of already existing policies 
- Provide UI functionality to copy an existing policy to another service

The policy then is contained multiple times in the storage, for both services, but effects of changing a single policy are much clearer. But I think this goes beyond the SUNFISH contribution

>  How the requestorID should be used?

I think the requestorID is some kind of crypto token introduced in the first version of the policy registry interface by Sadek. It is used to authenticate the requesting entity, but I don't think we already agreed on concrete mechanisms.

>  Should we manage the serviceId?

The service ID should be generated by the FAM during service deployment.

**Comment by andreamargheri** [comment]
> > How to assign the Policy to multiple Services? 

> I think we should add an API I don't think that we need this functionality on storage level! Of course it would minimize the storage size, but this is not the goal of key-value like storages (like NoSQL - MongoDB). Just imagine the impact of changing a single policy linked to multiple services.

> This is functionality which could be moved to user interface level, like:
> Provide a list of already existing policies 
> Provide UI functionality to copy an existing policy to another service
> The policy then is contained multiple times in the storage, for both services, but effects of changing a single policy are much clearer. But I think this goes beyond the SUNFISH contribution

Yes, I agree with this point. We will proceed as suggested. 

> > How the requestorID should be used?

> I think the requestorID is some kind of crypto token introduced in the first version of the policy registry interface by Sadek. It is used to authenticate the requesting entity, but I don't think we already agreed on concrete mechanisms.

Yes, you are right. We leave it as-is for the moment, we will support authN controls in the next iterations. Indeed, we won't implement any logic on the requestorID on the interface side.

**Comment by andreamargheri** [comment]
@areiter we finalised the api, but we need additional information on how to manage associations between ServiceID and PolicyID. 

Let's assume we have the following state 

<S_1, [P_1]> 

where to the service *S_1* the policy *P_1* is associated. Now, if a new **policy store** with argument a policy *P_2* and the same service *S_1*, the back-end logic should manage it resulting the following state

<S_1, [P_1, P_2]> 

However, let's assume now we want to remove *P_1* from the list of associated policies. This cannot be done via current API. We think this functionality should be supported. To this aim, there might be two possible options: 

1. add a *removeServicePolicy* API with argument (ServiceID, PolicyID) that removes the association between service and policy

2. change the store API, but not sure how. Maybe introducing a new parameter, but it would not be advocated.

**Comment by areiter** [comment]
@andreamargheri  According to [1] the `/policy/store` endpoint adds a policy and exclusively associates it with the provided serviceID. There is no way to link one policy to multiple services.
The `/policy/delete` endpoint in contrast, removes a policy (and also its association to the service).

Am I missing something?

[1] https://github.com/sunfish-prj/SUNFISH-Platform-API/blob/master/RegistryInterfaceAPI/swagger/RegistryInterface.yaml

**Comment by andreamargheri** [comment]
Ok, but this means that a higher-level component (eg FAM or PAP) will have to take care of it. That's fine with us, we will proceed this way. 

Notably, there is still room for strange updates, that we will manage returning 400 response. E.g., let's assume we have this state

<P1, {pol}> 
< S1, [P1]> 

and a new store(P1, {pol'}, ..., S2) is called, hence trying to update the policy {pol} and changing its service association. This won't be supported, first a delete is needed then a new store. A store can be used as an update but just to modify its policy body {pol} and/or its expiration time, without reporting any ServiceID (indeed it is optional)

Do you agree?

**Comment by areiter** [comment]
> Ok, but this means that a higher-level component (eg FAM or PAP) will have to take care of it. That's fine with us, we will proceed this way.

In think the FAM at GUI level should take care of it. In my opinion, this makes the underlying components more flexible (PAP, PEP, RI)

> This won't be supported, first a delete is needed then a new store. A store can be used as an update but just to modify its policy body {pol} and/or its expiration time, without reporting any ServiceID (indeed it is optional)

I agree. Just to fully understand your example, after applying the change to P1, is P1 associated only with S2 or with S1 and S2?
In my opinion P1 can only be associated with a single service at the same time.

**Comment by andreamargheri** [comment]
just S2, the S1 association is deleted. I'll close the issue
